import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { authenticator } from 'otplib';
import { randomBytes, createHash } from 'crypto';
import { toDataURL } from 'qrcode';
import {
  TwoFactorSetupResult,
  TwoFactorVerifyResult,
  TwoFactorBackupCode,
  TwoFactorConfig,
} from './interfaces/two-factor.interfaces';

/**
 * Service for TOTP-based two-factor authentication (2FA).
 *
 * @description Generates TOTP secrets and QR codes, verifies codes using
 * the `otplib` library, and manages backup codes for account recovery.
 * Configuration is read from the `twoFactor` section of the auth config.
 */
@Injectable()
export class TwoFactorService implements OnModuleInit {
  private readonly logger = new Logger(TwoFactorService.name);
  private readonly backupCodes: Map<string, TwoFactorBackupCode[]> = new Map();
  private issuer: string = 'MyApp';
  private algorithm: 'SHA1' | 'SHA256' | 'SHA512' = 'SHA1';
  private digits: 6 | 8 = 6;
  private period: number = 30;
  private backupCodesCount: number = 10;
  private backupCodesLength: number = 10;

  constructor(private readonly configService: ConfigService) {}

  onModuleInit() {
    this.loadConfig();
    this.logger.log(`✅ TwoFactorService initialized - Issuer: ${this.issuer}`);
  }

  private loadConfig() {
    const config = this.configService.get<{ twoFactor: TwoFactorConfig }>('auth');
    if (config?.twoFactor) {
      this.issuer = config.twoFactor.issuer || 'MyApp';
      this.algorithm = config.twoFactor.algorithm || 'SHA1';
      this.digits = config.twoFactor.digits || 6;
      this.period = config.twoFactor.period || 30;
      this.backupCodesCount = config.twoFactor.backupCodes?.count || 10;
      this.backupCodesLength = config.twoFactor.backupCodes?.length || 10;
    }
  }

  /**
   * Generates a new TOTP secret, QR code (data URL), and backup codes.
   *
   * @param userId - The user to generate 2FA credentials for
   * @returns A {@link TwoFactorSetupResult} with secret, otpauth URL, QR code, and backup codes
   */
  async generateSecret(userId: string): Promise<TwoFactorSetupResult> {
    const secret = authenticator.generateSecret();
    const otpauthUrl = authenticator.keyuri(userId, this.issuer, secret);
    const qrCode = await this.provideQrCode(otpauthUrl);
    const backupCodes = this.generateBackupCodes(userId);

    this.logger.log(`2FA secret generated for user: ${userId}`);

    return {
      secret,
      otpauthUrl,
      qrCode,
      backupCodes,
    };
  }

  /**
   * Converts an otpauth URL into a QR code data URL suitable for `<img>` tags.
   *
   * @param otpauthUrl - The `otpauth://` URI generated by the authenticator
   * @returns A base64 data URL string (or empty string on failure)
   */
  async provideQrCode(otpauthUrl: string): Promise<string> {
    try {
      return await toDataURL(otpauthUrl);
    } catch (error) {
      this.logger.error(`Failed to generate QR code: ${error instanceof Error ? error.message : String(error)}`);
      return '';
    }
  }

  /**
   * Verifies a TOTP code or backup code for a given user.
   *
   * @param userId - The user to verify the code for
   * @param code - The 6- or 8-digit code to verify
   * @returns A {@link TwoFactorVerifyResult} indicating validity
   */
  async verifyCode(userId: string, code: string): Promise<TwoFactorVerifyResult> {
    const backupCodes = this.backupCodes.get(userId) || [];

    if (backupCodes.some(bc => !bc.isUsed && this.verifyBackupCode(code, bc.hashedCode))) {
      return { valid: true };
    }

    const isValid = authenticator.verify({ token: code, secret: this.getUserSecret(userId) });

    return { valid: isValid };
  }

  /**
   * Enables 2FA for a user after verifying a valid TOTP code.
   *
   * @param userId - The user to enable 2FA for
   * @param code - A valid TOTP code to confirm setup
   * @returns Result with success flag and new backup codes if enabled
   */
  async enableTwoFactor(userId: string, code: string): Promise<{ success: boolean; backupCodes?: string[] }> {
    const isValid = authenticator.verify({ token: code, secret: this.getUserSecret(userId) });

    if (!isValid) {
      this.logger.warn(`Invalid 2FA code for user: ${userId}`);
      return { success: false };
    }

    const backupCodes = this.generateBackupCodes(userId);
    this.logger.log(`2FA enabled for user: ${userId}`);

    return { success: true, backupCodes };
  }

  /**
   * Disables 2FA for a user, removing all associated backup codes.
   *
   * @param userId - The user to disable 2FA for
   */
  async disableTwoFactor(userId: string): Promise<void> {
    this.backupCodes.delete(userId);
    this.logger.log(`2FA disabled for user: ${userId}`);
  }

  /**
   * Generates a set of single-use backup codes for account recovery.
   *
   * @description Each code is hashed with SHA-256 before storage.
   * Plaintext codes are returned once — they should be shown to the user
   * immediately and never stored in plaintext.
   *
   * @param userId - The user to generate backup codes for
   * @returns Array of plaintext backup codes
   */
  generateBackupCodes(userId: string): string[] {
    const codes: string[] = [];

    for (let i = 0; i < this.backupCodesCount; i++) {
      const code = this.generateBackupCode();
      const hashedCode = this.hashBackupCode(code);

      const existing = this.backupCodes.get(userId) || [];
      existing.push({ code, hashedCode, isUsed: false });
      this.backupCodes.set(userId, existing);

      codes.push(code);
    }

    this.logger.log(`Generated ${codes.length} backup codes for user: ${userId}`);

    return codes;
  }

  /**
   * Verifies a backup code and marks it as used if valid.
   *
   * @param userId - The user attempting to use a backup code
   * @param backupCode - The plaintext backup code to verify
   * @returns `true` if the code is valid and not yet used
   */
  async verifyBackupCodeWithUser(userId: string, backupCode: string): Promise<boolean> {
    const userBackupCodes = this.backupCodes.get(userId) || [];

    const found = userBackupCodes.find(bc => !bc.isUsed && this.verifyBackupCode(backupCode, bc.hashedCode));

    if (found) {
      found.isUsed = true;
      found.usedAt = new Date();
      this.logger.log(`Backup code used for user: ${userId}`);
      return true;
    }

    return false;
  }

  /**
   * Invalidates all existing backup codes and generates a fresh set.
   *
   * @param userId - The user to regenerate codes for
   * @param currentCode - A valid TOTP code to authorize regeneration
   * @returns Array of new plaintext backup codes
   * @throws Error if the current TOTP code is invalid
   */
  async regenerateBackupCodes(userId: string, currentCode: string): Promise<string[]> {
    const isValid = authenticator.verify({ token: currentCode, secret: this.getUserSecret(userId) });

    if (!isValid) {
      throw new Error('Invalid 2FA code');
    }

    this.backupCodes.delete(userId);
    const newCodes = this.generateBackupCodes(userId);

    this.logger.log(`Regenerated backup codes for user: ${userId}`);

    return newCodes;
  }

  /**
   * Checks whether 2FA is currently enabled for the given user.
   *
   * @param userId - The user to check
   * @returns `true` if backup codes exist for the user
   */
  isTwoFactorEnabled(userId: string): boolean {
    return this.backupCodes.has(userId) && this.backupCodes.get(userId)!.length > 0;
  }

  private generateBackupCode(): string {
    return randomBytes(this.backupCodesLength)
      .toString('base64')
      .replace(/\+/g, '0')
      .replace(/\//g, '1')
      .replace(/=/g, '')
      .substring(0, this.backupCodesLength)
      .toUpperCase();
  }

  private hashBackupCode(code: string): string {
    return createHash('sha256').update(code).digest('hex');
  }

  private verifyBackupCode(input: string, hashed: string): boolean {
    const inputHashed = this.hashBackupCode(input);
    return inputHashed === hashed;
  }

  private getUserSecret(userId: string): string {
    return `secret_for_${userId}`;
  }

  /**
   * Returns the number of seconds remaining in the current TOTP time window.
   *
   * @returns Seconds until the current code expires
   */
  getTimeRemaining(): number {
    const epoch = Math.floor(Date.now() / 1000);
    return this.period - (epoch % this.period);
  }
}